### ISSUE TITLE
.uni8( ) test failing

### ISSUE THREAD

**Issue by JonathanDDuncan** [Slevinski/SuttonSignWriting#1]
I was just running the tests on a fork of this project and got and error.  Ran it here without any of my modifications and it gives the same error.
Just wanted to let you know

https://slevinski.github.io/SuttonSignWriting/components/tests/index.html

.uni8( )
Valid
should return 1 to 3 Unicode 8 characters for key ‣
AssertionError: expected '𝠀𝪚𝪠' to equal '𝠀'
    at context.<anonymous> (https://slevinski.github.io/SuttonSignWriting/components/tests/test.ssw.js:199:14)
    at callFn (https://slevinski.github.io/SuttonSignWriting/include/vendor/mocha.js:4428:21)
    at Test.Runnable.run (https://slevinski.github.io/SuttonSignWriting/include/vendor/mocha.js:4421:7)
    at Runner.runTest (https://slevinski.github.io/SuttonSignWriting/include/vendor/mocha.js:4823:10)
    at https://slevinski.github.io/SuttonSignWriting/include/vendor/mocha.js:4901:12
    at next (https://slevinski.github.io/SuttonSignWriting/include/vendor/mocha.js:4748:14)
    at https://slevinski.github.io/SuttonSignWriting/include/vendor/mocha.js:4758:7
    at next (https://slevinski.github.io/SuttonSignWriting/include/vendor/mocha.js:4696:23)
    at https://slevinski.github.io/SuttonSignWriting/include/vendor/mocha.js:4725:5
    at timeslice (https://slevinski.github.io/SuttonSignWriting/include/vendor/mocha.js:5989:27)

**Comment by Slevinski** [comment]
I updated the uni8 function to keep F1 and R1 without updating the test suite. I did this for the .unicode() function to support the upcoming Unicode proposal for the additional 17 characters.

I do not see the value/utility of the variable length symbol definitions.  

@JonathanDDuncan , Do you have an opinion?

**Comment by JonathanDDuncan** [comment]
I don't think I understand most of the implications.  From what I understand, before we were doing 3 character unicode symbols now we have switched to 1 character unicode symbols.  

I think that for me as long as the value we put in the html makes the browser show the symbol, I don't really care if it takes one or three characters.

Should maybe update the test so that it doesn't fail though.

Thanks

Jonathan
